package allen;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class Hello
 */
@WebServlet("/Hello")
public class Hello extends HttpServlet {
	private static final long serialVersionUID = -1101746715763086941L;

	/**
	 * @see HttpServlet#HttpServlet()
	 */
	public Hello() {
		super();
	}

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		PrintWriter out = response.getWriter();
		out.print("Hello World, generated by Hello.java");
		
//		String destination = "welcome.jsp";
//		RequestDispatcher requestDispatcher = request.getRequestDispatcher(destination);
//		
//		String name = "John";
//		request.setAttribute("name", name);
//		 
//		Integer numberOfItems = 1000;
//		request.setAttribute("itemCount", numberOfItems);
//		 
//		List<String> fruits = Arrays.asList("Apple", "Banana", "Lemon", "Papaya");
//		request.setAttribute("itemCount", numberOfItems);
//		
//		requestDispatcher.forward(request, response);
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
